name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git \
            zip \
            unzip \
            openjdk-17-jdk \
            autoconf \
            automake \
            libtool \
            pkg-config \
            libffi-dev \
            libssl-dev

      - name: Install Buildozer
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install "cython<3" buildozer

      - name: Accept Android SDK licenses
        run: |
          mkdir -p "$ANDROID_HOME/licenses"

          echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
          echo "d56f5187479451eabf01fb78af6dfcb131a6481e7" >> "$ANDROID_HOME/licenses/android-sdk-license"
          echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" >> "$ANDROID_HOME/licenses/android-sdk-license"
      - name: Install Android SDK Build Tools
        run: |
          sdkmanager "build-tools;37.0.0" "platform-tools"
          
      - name: Show Android environment
        run: |
          echo "ANDROID_HOME=$ANDROID_HOME"
          java -version
          python --version
          buildozer --version

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: BusinessManager-APK
          path: bin/*.apk
          if-no-files-found: error
